# Generated by Django 5.2.10 on 2026-01-22 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evidence', '0011_add_file_status_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='evidencefile',
            name='submission_notes',
            field=models.TextField(blank=True, help_text='Notes provided when this file was submitted'),
        ),
    ]
