# Generated by Django 5.2.10 on 2026-01-29 09:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evidence', '0012_add_file_submission_notes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserGoogleDriveToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.TextField()),
                ('refresh_token', models.TextField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='google_drive_token', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Google Drive Token',
                'verbose_name_plural': 'User Google Drive Tokens',
            },
        ),
    ]
